# 运行模式 dev or prod
runmode: dev
# 静态文件版本
staticversion: 1
# superfeedr url
feedrurl: https://deepzz.superfeedr.com/
# 热搜词配置
hotwords:
  - docker
  - mongodb
  - curl
  - dns
# ping rpcs 地址
pingrpcs:
  - http://ping.baidu.com/ping/RPC2
  - http://blogsearch.google.com/ping/RPC2
  - http://rpc.pingomatic.com/
# 常规配置
general:
  # 首页展示文章数量
  pagenum: 10
  # 管理界面
  pagesize: 20
  # 起始ID，预留id不时之需, 不用管
  startid: 11
  # 文章描述前缀
  descprefix: "Desc:"
  # 截取预览标识
  identifier: <!--more-->
  # 自动截取预览, 字符数
  length: 400
  # 回收箱保留48小时
  trash: -48
  # 定时清理回收箱，每 %d 小时
  clean: 1
# 评论相关
disqus:
  shortname: xxxxxx
  publickey: wdSgxRm9rdGAlLKFcFdToBe3GT4SibmV7Y8EjJQ0r4GWXeKtxpopMAeIeoI2dTEg
  accesstoken: 50023908f39f4607957e909b495326af
  postscount: https://disqus.com/api/3.0/threads/set.json
  postslist: https://disqus.com/api/3.0/threads/listPosts.json
  postcreate: https://disqus.com/api/3.0/posts/create.json
  postapprove: https://disqus.com/api/3.0/posts/approve.json
  threadcreate: https://disqus.com/api/3.0/threads/create.json
  # 获取评论数量间隔
  interval: 5
# 谷歌统计
google:
  url: https://www.google-analytics.com/collect
  tid: UA-xxxxxx-1
  v: "1"
  t: pageview
# 七牛CDN
qiniu:
  bucket: eiblog
  domain: st.deepzz.com
  accesskey: MB6AXl_Sj_mmFsL-Lt59Dml2Vmy2o8XMmiCbbSeC
  secretkey: BIrMy0fsZ0_SHNceNXk3eDuo7WmVYzj2-zrmd5Tf
# 运行模式
mode:
  # http server
  enablehttp: true
  httpport: 9000
  # https server
  enablehttps: false
  autocert: false
  httpsport: 9001
  certfile: conf/ssl/domain.rsa.pem
  keyfile: conf/ssl/domain.rsa.key
  domain: deepzz.com
# twitter地址: twitter.com/chenqijing2
twitter:
  card: summary
  site: chenqijing2
  image: st.deepzz.com/static/img/avatar.jpg
  address: twitter.com/chenqijing2

# 数据初始化操作，可到博客后台修改
account:
  # *后台登录用户名
  username: deepzz
  # *登录明文密码
  password: deepzz
  # 邮箱，用于通知: chenqijing2@163.com
  email: chenqijing2@163.com
  # 手机号, "+8615100000000"
  phonenumber: "+8615100000000"
  # 家庭住址
  address: ""

database:
  type: mysql
  host: db.limon.com:3306
  name: limon_dev
  user: dev
  password: 123456
  MAX_OPEN_CONNS: 30
  MAX_IDLE_CONNS: 30